In [16]:
from google.colab import files
uploaded = files.upload()

Saving Walmart.csv to Walmart (1).csv

In [18]:
import pandas as pd

df = pd.read_csv("Walmart (1).csv")

In [19]:
df.shape

(10051, 11)

In [20]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48

In [21]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [23]:
df.duplicated().sum()

np.int64(51)

In [25]:
df.drop_duplicates(inplace=True)

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.shape

(10000, 11)

In [28]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [29]:
#dropping all rows with missing records
df.dropna(inplace=True)

In [30]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [31]:
df.shape

(9969, 11)

In [32]:
df['unit_price'] = df['unit_price'].str.replace('$','').astype(float)

df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 1.2+ MB

In [34]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [35]:
df['total'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48,604.17

In [36]:
df.to_csv('walmart_cleaned.csv', index=False)

In [37]:
import os
os.listdir()

['.config',
 'Walmart.csv',
 'walmart_cleaned.csv',
 'Walmart (1).csv',
 'walmart_feature_engineered.csv',
 'sample_data']

In [38]:
from google.colab import files
files.download('walmart_cleaned.csv')

In [39]:
print("Rows after cleaning:", df.shape[0])

print("Duplicates left:", df.duplicated().sum())

print("Null values left:")
print(df.isnull().sum())

Rows after cleaning: 9969
Duplicates left: 0
Null values left:
invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
total             0
dtype: int64

In [40]:
df.to_csv('walmart_cleaned.csv', index=False)

from google.colab import files
files.download('walmart_cleaned.csv')

In [43]:
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

df['day_name'] = df['date'].dt.day_name()
df['month_name'] = df['date'].dt.month_name()
df['year'] = df['date'].dt.year

In [44]:
df[['date','day_name','month_name','year']].head()

        date  day_name month_name  year
0 2019-01-05  Saturday    January  2019
1 2019-03-08    Friday      March  2019
2 2019-03-03    Sunday      March  2019
3 2019-01-27    Sunday    January  2019
4 2019-02-08    Friday   February  2019

In [45]:
def get_shift(time):
    hour = pd.to_datetime(time).hour

    if hour < 12:
        return 'Morning'
    elif hour < 17:
        return 'Afternoon'
    else:
        return 'Evening'

df['shift'] = df['time'].apply(get_shift)

In [46]:
df[['time','shift']].head()

       time      shift
0  13:08:00  Afternoon
1  10:29:00    Morning
2  13:23:00  Afternoon
3  20:33:00    Evening
4  10:37:00    Morning

In [47]:
df.to_csv('walmart_feature_engineered.csv', index=False)

In [48]:
from google.colab import files
files.download('walmart_feature_engineered.csv')